# Generated by Django 4.0.5 on 2022-06-17 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Usuarios', '0001_initial'),
        ('Boleta', '0001_initial'),
        ('Pasajes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boleta',
            name='ticket',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Pasajes.pasajes', verbose_name='Pasaje'),
        ),
        migrations.AddField(
            model_name='boleta',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Usuarios.usuarios', verbose_name='Usuario'),
        ),
    ]
