# Generated by Django 4.0.5 on 2022-06-17 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre de Usuario')),
                ('lastname', models.CharField(max_length=100, verbose_name='Apellido de Usuario')),
                ('DNI', models.BigIntegerField(verbose_name='DNI')),
                ('cellphone', models.BigIntegerField(verbose_name='Numero de Celular')),
                ('address', models.CharField(max_length=100, verbose_name='Direccion')),
                ('email', models.EmailField(max_length=200, verbose_name='email')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creacion')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualizacion')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
    ]
