# Generated by Django 4.0.5 on 2022-06-17 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pasajes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=100, verbose_name='Origen')),
                ('destiny', models.CharField(max_length=100, verbose_name='Destino')),
                ('num_chair', models.IntegerField(verbose_name='Numero de Asiento')),
                ('cost', models.FloatField(verbose_name='Precio')),
                ('state', models.BooleanField(default=True, verbose_name='Cancelado')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creacion')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualizacion')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Usuarios.usuarios', verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Pasaje',
                'verbose_name_plural': 'Pasajes',
            },
        ),
    ]
